Feature/person overview
WormBase/wormbase_rest pull request #81
Opened 2017-02-15 01:05 UTC by azurebrd

Linting with 'lein eastwood'
There are 2 warnings from gene_test.clj and 1 warning from test_routing.clj, which I didn't modify, so I don't know whether warnings are okay to ignore.
There are 2 warnings from publications.clj about def-in-def. I don't know why it's bad, nor alternatively, how to get around doing group-by without defining results into a new variable.

2017-02-15 05:45 UTC, sibyl229 commented
Hi @azurebrd def-in-def is probably not what you want, because `def` is global to the namespace, maybe what you need is `let`? 

I haven't tried eastwood lately to know if the other warnings are okay.

I think the code is nice. I'm happy with everything else. Just some indentations are off, can you try have your text editor reindent everything?

2017-02-15 06:02 UTC, azurebrd commented
Thanks @sibyl229 ! I'll try out let tomorrow, and I remember now Adam telling me about vim-fireplace for the indenting.

2017-02-15 08:56 UTC, mgrbyte reviewed
Generally, logic looks good.
Style-wise, we're trying to keep to "standard" clojure conventions:
  naming: var-names-like-this
  spacing: 2 space indent
  braces brackets wrap up (never on their own line)

2017-02-15 08:56 UTC, mgrbyte commented on src/rest_api/classes/person/widgets/publications.clj
> +         dataArrayTuples
Suggest renaming `dataArrrayTuples` to just `data` or `datoms`

2017-02-15 08:56 UTC, mgrbyte commented on src/rest_api/classes/person/widgets/publications.clj
> +     (def data (group-by :year dataArrayTuples))
You can eliminate the `eastwood` warnings by removing this line (32),
and adding `((group-by :year))` as the final step in the `->>` pipeline, just below `(seq)` above.

2017-02-15 08:56 UTC, mgrbyte commented on src/rest_api/classes/person/widgets/publications.clj
> +     (def data (group-by :year dataArrayTuples))
Same as above w/regard to naming and eliminating `lein eastwood` warnings.

2017-02-15 09:02 UTC, mgrbyte commented on src/rest_api/classes/person/widgets/laboratory.clj
> +(defn gene-classes [person]
Could this be re-worked so just one datomic query is made?
Currently: 1 + number-of-labs-per-person queries.

Something like:
```clojure
(d/q '[:find [?geneclass ...]
         :where
         [?lab :laboratory/registered-lab-members ?person]
         [?geneclass :gene-class/designating-laboratory ?lab]]
        db (:db/id person))
```

2017-02-15 18:37 UTC, azurebrd commented
Thanks @mgrbyte !  

The (seq)(group-by :year) worked great.

For reducing the number of gene class queries, it makes sense to query for all the gene classes of a given person, and follow them to the gene class's laboratory, but to get the :lab :label/:id is there a way to follow the gene_class without making a new query into each gene_class's laboratory ?  Something like this doesn't work
                      (let [geneclass (d/entity db oid)]
                                (let [geneclass (d/entity db oid)]
                                  (pace-utils/vmap
                                   :lab
                                      {:taxonomy "all"
                                       :class "laboratory"
                                       :label (:gene-class/designating-laboratory geneclass)
because it's the :ref entity instead of the :laboratory/id

In ACeDB gene_class xrefs many-to-one to laboratory, and laboratory xrefs uniquely to gene_class, so I've switched the order of the querying, gene_class first then laboratory within that, but that doesn't reduce the number of queries, just sort of returns the data in a more pair-like way.

If you meant that we can query for a person's laboratory and gene_class separately and aggregate them, a person can have multiple labs, and each gene_class has to be associated to its own laboratory.  If that weren't the case and we could aggregate the data off of separate queries, I wouldn't know how to write the syntax, but it'd be nice to know that it would be okay to do things that way.  I've been following the format of existing queries to generate the data, but there's been times that I've wanted to query things separately and aggregate afterward.

2017-02-15 20:20 UTC, mgrbyte commented on src/rest_api/classes/person/widgets/publications.clj
> +              (seq)(group-by :year))]
Nearly! 
Think you want:
```
...
(group-by :year)
(seq))
````

2017-02-15 21:55 UTC, adamjohnwright requested changes

2017-02-15 21:55 UTC, a8wright commented on src/rest_api/classes/person/widgets/laboratory.clj
> +                       )
You should pull these braces up

2017-02-15 21:55 UTC, a8wright commented on src/rest_api/classes/person/widgets/laboratory.clj
> +                     )))
You should pull these braces up

2017-02-15 21:55 UTC, a8wright commented on src/rest_api/classes/person/widgets/laboratory.clj
> +                        ) )))
You should pull these braces up

2017-02-15 21:55 UTC, a8wright commented on src/rest_api/classes/person/widgets/laboratory.clj
> +                     )))
You should pull these braces up

2017-02-15 21:55 UTC, a8wright commented on src/rest_api/classes/person/widgets/overview.clj
> +                      )
You should pull these braces up

2017-02-15 21:55 UTC, a8wright commented on src/rest_api/classes/person/widgets/publications.clj
> +  })
You should pull these braces up

2017-02-15 21:55 UTC, a8wright commented on src/rest_api/classes/person/widgets/tracking.clj
> +
Should remove extra lines like this one

2017-02-16 00:28 UTC, azurebrd commented
@a8wright Went through formatting with vim-fireplace and cleaned it up.

2017-02-16 01:02 UTC, adamjohnwright approved these changes

2017-02-16 01:03 UTC, a8wright commented
you will need to do a "git merge develop" and then fix the merge conflicts. Then do a merge commit. and push. I think it will be ready to pull at that point!  Great work!!

2017-02-16 02:24 UTC, merged

2017-02-16 02:33 UTC, azurebrd commented
@a8wright Thanks Adam !  I think it's done.  I ended up in the development branch, where I merged, fixed, and pushed it.  I then came back to this branch, merged in develop, saw the changes and it all runs well, so I think it's good.  I think I just didn't 'git pull' before merging develop, which is why it didn't have any changes in develop to merge.  Sorry about that.

2017-02-16 02:47 UTC, a8wright commented
@azurbrd No problem. I use the gitflow tool and it doesn't pull from develop for me. I thought the "git hf update" would do it but no such luck lately. I am glad you are able to get it merged.

2017-02-16 02:55 UTC, azurebrd commented
Thanks !